### ISSUE TITLE
Crash under heavy load

### ISSUE THREAD

**Issue by joshelson** [adrianhall/winston-splunk-httplogger#15]
I know this isn't actively being developed, but I have been seeing a crash of the following sort under heavy load. Not sure if anyone else has seen of if there's a solution available, but wanted to put it out there.

`2020-02-06 14:54 -05:00: ERROR: { Error: connect ECONNRESET 10.1.250.207:8088
2020-02-06 14:54 -05:00:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2020-02-06 14:54 -05:00: ---------------------------------------------
2020-02-06 14:54 -05:00:     at TLSSocket.Readable.on (_stream_readable.js:772:35)
2020-02-06 14:54 -05:00:     at tickOnSocket (_http_client.js:650:10)
2020-02-06 14:54 -05:00:     at onSocketNT (_http_client.js:680:5)
2020-02-06 14:54 -05:00:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
2020-02-06 14:54 -05:00:     at process._tickCallback (internal/process/next_tick.js:181:9)
2020-02-06 14:54 -05:00: ---------------------------------------------
2020-02-06 14:54 -05:00:     at ClientRequest.onSocket (_http_client.js:668:11)
2020-02-06 14:54 -05:00:     at handleSocketCreation_Inner (_http_agent.js:351:15)
2020-02-06 14:54 -05:00:     at oncreate (_http_agent.js:224:5)
2020-02-06 14:54 -05:00:     at Agent.createSocket (_http_agent.js:229:5)
2020-02-06 14:54 -05:00:     at Agent.addRequest (_http_agent.js:185:10)
2020-02-06 14:54 -05:00:     at new ClientRequest (_http_client.js:268:16)
2020-02-06 14:54 -05:00:     at Object.request (http.js:39:10)
2020-02-06 14:54 -05:00:     at Object.request (https.js:245:15)
2020-02-06 14:54 -05:00:     at Request.start (/home/offlineapps/ito-cati-screener-api/node_modules/request/request.js:751:32)
2020-02-06 14:54 -05:00:     at Request.write (/home/offlineapps/ito-cati-screener-api/node_modules/request/request.js:1497:10)
2020-02-06 14:54 -05:00:     at end (/home/offlineapps/ito-cati-screener-api/node_modules/request/request.js:549:18)
2020-02-06 14:54 -05:00:     at Immediate._onImmediate (/home/offlineapps/ito-cati-screener-api/node_modules/request/request.js:578:7)
2020-02-06 14:54 -05:00:     at runCallback (timers.js:810:20)
2020-02-06 14:54 -05:00:     at tryOnImmediate (timers.js:768:5)
2020-02-06 14:54 -05:00:     at processImmediate [as _immediateCallback] (timers.js:745:5)`

**Comment by adrianhall** [comment]
I don't have any mechanism by which to test this, or even reproduce this.  It looks like resource exhaustion, which means the problem is deep in the NodeJS environment, which also means there is nothing I can do about it in code.
